export const advertiseRequestsData = [
    {
        id: 1,
        serialNo: 'XHKSD0001',
        advertiseID: 'XYZ0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        type: 'Premium',
        days: '3',
        adTitle: 'XYZ',
        businessName: 'REAL ESTATE & BUILDING',
        businessContact: '9845872890',
        businessMail: 'xyz@gmail.com',
        location: 'Bangalore',
        pincode: '560098',
        requestedBy: '7487678923',
        requestedOn: '23-03-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        serialNo: 'XHKSD0002',
        advertiseID: 'XYZ0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        type: 'Premium',
        days: '3',
        adTitle: 'XYZ',
        businessName: 'REAL ESTATE & BUILDING',
        businessContact: '9845872890',
        businessMail: 'xyz@gmail.com',
        location: 'Bangalore',
        pincode: '560098',
        requestedBy: '7487678923',
        requestedOn: '23-03-2025',
        status: { tooltip: 'Deactive', color: 'danger' },
    },
];
export const draftAdvertiseListingsData = [
    {
        id: 1,
        serialNo: 'ABC0001',
        draftID: 'DRAFT0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        type: 'Premium',
        days: '3',
        adTitle: 'XYZ',
        businessName: 'REAL ESTATE & BUILDING',
        businessContact: '9845872890',
        businessMail: 'xyz@gmail.com',
        location: 'Bangalore',
        pincode: '560098',
        requestedBy: '7487678923',
        requestedOn: '23-03-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        serialNo: 'ABC0002',
        draftID: 'DRAFT0002',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        type: 'Premium',
        days: '3',
        adTitle: 'XYZ',
        businessName: 'REAL ESTATE & BUILDING',
        businessContact: '9845872890',
        businessMail: 'xyz@gmail.com',
        location: 'Bangalore',
        pincode: '560098',
        requestedBy: '7487678923',
        requestedOn: '23-03-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const supportQueriesData = [
    {
        id: 1,
        serialNo: 'SR0001',
        supportID: 'SUPPORTID0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        type: 'Premium',
        phone: '7487678923',
        businessMail: 'xyz@gmail.com',
        query: 'Some query about...',
        queryBy: '7487678923',
        queryOn: '23-03-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        serialNo: 'SR0002',
        supportID: 'SUPPORTID0002',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        type: 'Premium',
        phone: '7487678923',
        businessMail: 'xyz@gmail.com',
        query: 'Some query about...',
        queryBy: '7487678923',
        queryOn: '23-03-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const contentsData = [
    {
        id: 1,
        serialNo: 'SR0001',
        promoID: 'PROMOID0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        category: 'Category 1',
        phone: '7487678923',
        localityName: 'ABC',
        location: 'Bangalore',
        promoName: 'XYZ',
        title: 'ABC',
        visibleFrom: '08-04-2025',
        visibleTill: '10-04-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        serialNo: 'SR0002',
        promoID: 'PROMOID0002',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        category: 'Category 2',
        phone: '7487678923',
        localityName: 'ABC',
        location: 'Bangalore',
        promoName: 'XYZ',
        title: 'ABC',
        visibleFrom: '09-04-2025',
        visibleTill: '08-05-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const listingsData = [
    {
        id: 1,
        serialNo: 'SR0001',
        advertiseID: 'ADV0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        type: 'Premium',
        days: '6',
        adTitle: 'ASDF',
        businessName: 'REAL ESTATE & BUILDING',
        businessContact: '9845872890',
        businessMail: 'xyz@gmail.com',
        location: 'Bangalore',
        pincode: '560098',
        requestedBy: '7487678923',
        requestedOn: '23-03-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        serialNo: 'SR0002',
        advertiseID: 'ADV0002',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        type: 'Premium',
        days: '6',
        adTitle: 'ASDF',
        businessName: 'REAL ESTATE & BUILDING',
        businessContact: '9845872890',
        businessMail: 'xyz@gmail.com',
        location: 'Bangalore',
        pincode: '560098',
        requestedBy: '7487678923',
        requestedOn: '23-03-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const rejectedListingsData = [
    {
        id: 1,
        serialNo: 'SR0001',
        advertiseID: 'ADV0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        type: 'Premium',
        days: '6',
        adTitle: 'ASDF',
        businessName: 'REAL ESTATE & BUILDING',
        businessContact: '9845872890',
        businessMail: 'xyz@gmail.com',
        location: 'Bangalore',
        pincode: '560098',
        requestedBy: '7487678923',
        requestedOn: '23-03-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        serialNo: 'SR0002',
        advertiseID: 'ADV0002',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        type: 'Premium',
        days: '6',
        adTitle: 'ASDF',
        businessName: 'REAL ESTATE & BUILDING',
        businessContact: '9845872890',
        businessMail: 'xyz@gmail.com',
        location: 'Bangalore',
        pincode: '560098',
        requestedBy: '7487678923',
        requestedOn: '23-03-2025',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const promoHelpsData = [
    {
        id: 1,
        serialNo: 'SR0001',
        helpID: 'HELP0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        helpTitle: 'HELP PROMO',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        serialNo: 'SR0002',
        helpID: 'HELP0002',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        helpTitle: 'HELP PROMO',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const promoDisclaimersData = [
    {
        id: 1,
        serialNo: 'SR0001',
        disclaimerID: 'HELP0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        disclaimerTitle: 'HELP PROMO',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        serialNo: 'SR0002',
        disclaimerID: 'HELP0002',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        disclaimerTitle: 'HELP PROMO',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const faqsData = [
    {
        id: 1,
        serialNo: 'SR0001',
        faqID: 'HELP0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        faqTitle: 'HELP PROMO',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        serialNo: 'SR0002',
        faqID: 'HELP0002',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        faqTitle: 'HELP PROMO',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const supportsData = [
    {
        id: 1,
        serialNo: 'SR0001',
        supportID: 'HELP0001',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        supportTitle: 'HELP PROMO',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        serialNo: 'SR0002',
        supportID: 'HELP0002',
        imageUrl: 'https://img.freepik.com/free-psd/real-estate-template-design_23-2150221888.jpg?semt=ais_hybrid&w=740',
        supportTitle: 'HELP PROMO',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const categoriesData = [
    {
        id: 1,
        categoryName: 'Category 1',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        categoryName: 'Category 2',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const subcategoriesData = [
    {
        id: 1,
        categoryName: 'Category 1',
        subcategoryName: 'Subcategory 1',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        categoryName: 'Category 2',
        subcategoryName: 'Subcategory 2',
        status: { tooltip: 'Active', color: 'success' },
    },
];
export const statesData = [
    {
        id: 1,
        stateName: 'Karnataka',
        status: { tooltip: 'Active', color: 'success' },
    },
    {
        id: 2,
        stateName: 'Odisha',
        status: { tooltip: 'Deactive', color: 'danger' },
    },
];
